# Generated by Django 2.2 on 2019-04-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BCH', 'Bitcoin Cash'), ('LTC', 'Litecoin')], default='USD', max_length=3),
            preserve_default=False,
        ),
    ]
