# Generated by Django 2.2 on 2019-04-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingate', '0003_order_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(verbose_name='order id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='payment url'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_amount',
            field=models.FloatField(verbose_name='price amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BCH', 'Bitcoin Cash'), ('LTC', 'Litecoin')], max_length=3, verbose_name='price currency'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
