# Generated by Django 2.2 on 2019-04-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coingate', '0004_auto_20190420_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
